# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20151120_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
