# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_remove_institution_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='institution',
            name='last_sync',
            field=models.DateTimeField(null=True),
        ),
    ]
