# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institution_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='plaid_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
