# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_institution_reauth_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='plaid_public_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
