# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_auto_20160425_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='access_token',
            new_name='plaid_access_token',
        ),
    ]
