# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_auto_20160425_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/institution/logo'),
        ),
    ]
