# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 13:19
from __future__ import unicode_literals

from django.db import migrations


def finicity_logos(apps, schema_editor):
    FinicityInstitution = apps.get_model('finicity', 'FinicityInstitution')
    Institution = apps.get_model('institutions', 'Institution')

    for finicity_institution in FinicityInstitution.objects.all():
        if not finicity_institution.image:
            continue
        Institution.objects.filter(
            finicity_id=finicity_institution.finicity_id,
        ).update(logo=finicity_institution.image)


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_institution_logo'),
        ('finicity', '0004_auto_20160406_1628'),
    ]

    operations = [
        migrations.RunPython(finicity_logos),
    ]
