# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 13:29
from __future__ import unicode_literals

from base64 import b64decode

from django.db import migrations
from django.core.files.base import ContentFile

import requests


def plaid_logos(apps, schema_editor):
    Institution = apps.get_model('institutions', 'Institution')

    for institution in Institution.objects.filter(plaid_id__isnull=False):
        response = requests.get(
            'https://tartan.plaid.com/institutions/search?id={}'.format(institution.plaid_id)
        )
        if response.status_code == 200 and 'logo' in response.json():
            institution.logo = ContentFile(b64decode(response.json()['logo']), 'logo.png')
            institution.save()


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_auto_20160527_1319'),
    ]

    operations = [
        migrations.RunPython(plaid_logos),
    ]
