# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 19:52
from __future__ import unicode_literals

from django.db import migrations


def migrate_institutions(apps, schema_editor):
    FinicityInstitution = apps.get_model('finicity', 'FinicityInstitution')
    InstitutionTemplate = apps.get_model('institutions', 'InstitutionTemplate')

    for finicity_institution in FinicityInstitution.objects.all():
        InstitutionTemplate.objects.create(
            name=finicity_institution.name,
            url=finicity_institution.url,
            finicity_id=finicity_institution.finicity_id,
            color=finicity_institution.color,
            image=finicity_institution.image,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_institutiontemplate'),
        ('finicity', '0004_auto_20160406_1628'),
    ]

    operations = [
        migrations.RunPython(migrate_institutions),
    ]
