# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_auto_20160607_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutiontemplate',
            name='default',
            field=models.CharField(blank=True, choices=[('', 'Search Only'), ('us', 'USA'), ('ca', 'Canada')], default='', max_length=20),
        ),
    ]
