# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0014_institutiontemplate_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiontemplate',
            name='finicity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institutiontemplate',
            name='plaid_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
