# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0015_auto_20160607_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiontemplate',
            name='color',
            field=models.CharField(default='#000000', max_length=21),
        ),
    ]
