# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_updated',
        ),
    ]
