# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20151120_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 20, 16, 21, 24, 162064, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 11, 20, 16, 21, 27, 753839, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
