# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20151120_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_available',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_snippet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='plaid_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
