# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance_available',
            new_name='available_balance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='balance_current',
            new_name='current_balance',
        ),
    ]
