# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160210_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='disabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
