# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160210_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='finicity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
