rules:
  property-sort-order:
    - 0
  placeholder-in-extend:
    - 0
  single-line-per-selector:
    - 0
  no-color-keywords:
    - 0
  no-color-literals:
    - 0
  border-zero:
    - 0
  nesting-depth:
    - 0
  force-element-nesting:
    - 0
  force-pseudo-nesting:
    - 0
  no-qualifying-elements:
    - 0
