# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finicity', '0003_finicityinstitution_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finicityinstitution',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
