# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finicity', '0004_auto_20160406_1628'),
        ('institutions', '0010_auto_20160527_1319'),
        ('institutions', '0013_auto_20160607_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinicityInstitution',
        ),
    ]
