# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160505_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
