# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_entry_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
