# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 15:11
from __future__ import unicode_literals

from django.db import migrations
import resize.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160519_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='secondary_color',
        ),
        migrations.AlterField(
            model_name='category',
            name='hero_art',
            field=resize.fields.ResizedImageField(resolutions=('1920x700', '750x500'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='hero_art',
            field=resize.fields.ResizedImageField(resolutions=('1920x700', '750x500'), upload_to=''),
        ),
    ]
