# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160527_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='byline_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='byline_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
