# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField()),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plaid_id', models.CharField(blank=True, max_length=255, null=True)),
                ('address_city', models.CharField(max_length=255, null=True)),
                ('address_street', models.CharField(max_length=255, null=True)),
                ('address_state', models.CharField(max_length=255, null=True)),
                ('source', models.CharField(choices=[('csv', 'CSV'), ('plaid', 'Plaid Connect')], max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Account')),
                ('bucket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='buckets.Bucket')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('transfer_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction')),
                ('transfer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
