# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='bucket_month',
            new_name='bucket_months',
        ),
        migrations.AddField(
            model_name='transaction',
            name='savings',
            field=models.BooleanField(default=False),
        ),
    ]
