# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20160210_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='deleted',
        ),
    ]
