# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20160216_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_pair',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.Transaction'),
        ),
    ]
