# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='address_state',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='address_street',
        ),
        migrations.AddField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='buckets.Bucket'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='accounts.Account'),
        ),
    ]
