# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_auto_20160201_2152'),
        ('transactions', '0004_auto_20151120_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='buckets.Bucket'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plaid_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
