# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20160210_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('csv', 'CSV'), ('plaid', 'Plaid Connect')], default='plaid', max_length=255),
        ),
    ]
