# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20160217_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='spent_from_savings',
            new_name='from_savings',
        ),
    ]
