# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20160210_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_to',
        ),
    ]
