# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20160217_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_pair',
        ),
        migrations.AddField(
            model_name='transaction',
            name='_transfer_pair',
            field=models.ManyToManyField(related_name='_transaction__transfer_pair_+', to='transactions.Transaction'),
        ),
    ]
