# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20160219_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('csv', 'CSV'), ('plaid', 'Plaid Connect'), ('demo', 'Demo Data')], default='plaid', max_length=255),
        ),
    ]
