# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_incomefromsavings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
