# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 19:36
from __future__ import unicode_literals

from django.db import migrations


def remove_duplicates(apps, schema_editor):
    BucketTransaction = apps.get_model('transactions', 'BucketTransaction')
    last_pair = None
    for bucket_transaction in BucketTransaction.objects.order_by('bucket_month_id', 'transaction_id'):
        current_pair = [
            bucket_transaction.bucket_month_id,
            bucket_transaction.transaction_id,
        ]
        if current_pair == last_pair:
            bucket_transaction.delete()
        else:
            last_pair = current_pair


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20160315_2140'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AlterUniqueTogether(
            name='buckettransaction',
            unique_together=set([('bucket_month', 'transaction')]),
        ),
    ]
