# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20160329_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='finicity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
