# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20160412_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bucket',
            new_name='buckets',
        ),
    ]
