# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20160412_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='finicity_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plaid_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
