# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_remove_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='raw_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
