# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 18:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_transaction_raw_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
