# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-04 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20160630_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
