# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 20:53
from __future__ import unicode_literals

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_demo_user(apps, schema):
    User = apps.get_model('users', 'User')
    demo_user = User(email='demo@spendwell.co')
    demo_user.password = make_password('demo')
    demo_user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_demo_user),
    ]
