# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estimated_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
