# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 15:18
from __future__ import unicode_literals

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160224_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betacode',
            name='key',
            field=models.CharField(default=apps.users.models.get_beta_code, max_length=255),
        ),
    ]
