# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160225_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 16, 21, 25, 51, 456607, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 16, 21, 25, 57, 564616, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
