# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160316_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finicity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
