# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160330_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Toronto', max_length=100),
            preserve_default=False,
        ),
    ]
