# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='betacode',
            name='intended_for',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
