# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_dashboard_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Toronto', max_length=100),
        ),
    ]
