# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160413_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estimated_income_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
