# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20160601_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betacode',
            name='beta_signup',
        ),
        migrations.AddField(
            model_name='betasignup',
            name='beta_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beta_signup', to='users.BetaCode'),
        ),
    ]
