# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-16 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20160601_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
