# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-20 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20160630_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
