# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_email_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yodlee_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
