# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_remove_bucket_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('month_start', models.DateTimeField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='buckets.Bucket')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bucketmonth',
            unique_together=set([('bucket', 'month_start')]),
        ),
    ]
