# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_auto_20160211_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('bill', 'Bill')], default='expense', max_length=10),
        ),
    ]
