# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 22:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_auto_20160201_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'and': [], 'or': []}),
        ),
    ]
