# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0005_auto_20160304_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketmonth',
            options={'ordering': ('-month_start',)},
        ),
    ]
