# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0006_auto_20160308_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense Category'), ('bill', 'Bill'), ('account', 'External Account')], default='expense', max_length=10),
        ),
    ]
