# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20160412_2009'),
        ('buckets', '0008_auto_20160408_1939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bucketmonth',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='bucketmonth',
            name='bucket',
        ),
        migrations.DeleteModel(
            name='BucketMonth',
        ),
    ]
