# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0009_auto_20160412_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='filters',
            new_name='_filters',
        ),
    ]
