# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0010_auto_20160413_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='buckets/bucket/avatar'),
        ),
    ]
