# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0011_bucket_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='avatar',
        ),
    ]
