# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0012_remove_bucket_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='buckets/bucketavatar/avatar')),
            ],
        ),
    ]
