# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-22 13:44
from __future__ import unicode_literals

from django.db import migrations


def convert_external_accounts(apps, schema_editor):
    Bucket = apps.get_model('buckets', 'Bucket')
    for external_account in Bucket.objects.filter(type='account'):
        Bucket.objects.create(
            owner=external_account.owner,
            name=external_account.name,
            _filters=external_account._filters,
            goal_amount=0,
            type='goal',
        )
        external_account.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0014_auto_20160622_1336'),
    ]

    operations = [
        migrations.RunPython(convert_external_accounts),
    ]
