# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-22 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0015_auto_20160622_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='goal_amount',
            new_name='fixed_goal_amount',
        ),
    ]
