# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-03 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0016_auto_20160622_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='fixed_goal_amount',
            new_name='fixed_amount',
        ),
        migrations.AddField(
            model_name='bucket',
            name='use_fixed_amount',
            field=models.BooleanField(default=False),
        ),
    ]
