# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20160209_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
