# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goal_monthly_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goalmonth',
            unique_together=set([('goal', 'month_start')]),
        ),
    ]
