# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_auto_20160210_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalmonth',
            name='filled_amount',
        ),
    ]
