# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-22 13:36
from __future__ import unicode_literals

from django.db import migrations


def move_goals(apps, schema_editor):
    Goal = apps.get_model('goals', 'Goal')
    Bucket = apps.get_model('buckets', 'Bucket')
    for goal in Goal.objects.all():
        Bucket.objects.create(
            owner=goal.owner,
            name=goal.name,
            goal_amount=goal.monthly_amount,
            type='goal',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_remove_goalmonth_filled_amount'),
        ('buckets', '0014_auto_20160622_1336'),
    ]

    operations = [
        migrations.RunPython(move_goals),
    ]
